[package]
name = "koala-qos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
minstant = "0.1.1"
thiserror = "1.0.31"
nix = "0.23.0"
anyhow = "1.0.58"
serde = { version = "1.0.130", features = ["derive"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
bincode = "1.3.3"

koala = { path = "../../../koala" }
ipc = { path = "../../../ipc", features = ["qos"] }