#!/usr/bin/env bash
export OUT_DIR=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out

# export OUT_DIR=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out
# rustc --crate-name rdma --edition=2021 src/rdma/src/lib.rs --crate-type dylib --emit=dep-info,link -C embed-bitcode=no -C prefer-dynamic -C rpath -C debuginfo=2 --cfg 'feature="phoenix"' -C metadata=3ffb2efcda1f73f4 --out-dir /home/cjr/Developing/phoenix/target/debug/deps -C incremental=/home/cjr/Developing/phoenix/target/debug/incremental -L dependency=/home/cjr/Developing/phoenix/target/debug/deps --extern bincode=/home/cjr/Developing/phoenix/target/debug/deps/libbincode-859c160274644f51.rlib --extern lazy_static=/home/cjr/Developing/phoenix/target/debug/deps/liblazy_static-b33cd6b8ee13db74.rlib --extern libc=/home/cjr/Developing/phoenix/target/debug/deps/liblibc-054273bc4cae1e50.rlib --extern log=/home/cjr/Developing/phoenix/target/debug/deps/liblog-2aea261907451eb5.rlib --extern memfd=/home/cjr/Developing/phoenix/target/debug/deps/libmemfd-7791e2e50a1027b8.rlib --extern mmap=/home/cjr/Developing/phoenix/target/debug/deps/libmmap.so --extern nix=/home/cjr/Developing/phoenix/target/debug/deps/libnix-fa75e0b126df7a06.rlib --extern serde=/home/cjr/Developing/phoenix/target/debug/deps/libserde-0b53df5957df3f5c.rlib --extern socket2=/home/cjr/Developing/phoenix/target/debug/deps/libsocket2-d3b0309fc407eb23.rlib --extern spin=/home/cjr/Developing/phoenix/target/debug/deps/libspin-4b783b3a70ffaff7.rlib --extern static_assertions=/home/cjr/Developing/phoenix/target/debug/deps/libstatic_assertions-c94e2eb84119cf0b.rlib --extern thiserror=/home/cjr/Developing/phoenix/target/debug/deps/libthiserror-02ea2539be95b040.rlib --extern uapi=/home/cjr/Developing/phoenix/target/debug/deps/libuapi.so
# unset OUT_DIR

# export OUT_DIR=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out
# rustc --crate-name rdma --edition=2021 src/rdma/src/lib.rs --crate-type dylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="phoenix"' -C metadata=56aef714ffcc6993 --out-dir /home/cjr/Developing/phoenix/target/release/deps -L dependency=/home/cjr/Developing/phoenix/target/release/deps --extern bincode=/home/cjr/Developing/phoenix/target/release/deps/libbincode-157b6e3ae2e1dc50.rlib --extern lazy_static=/home/cjr/Developing/phoenix/target/release/deps/liblazy_static-1fabe01c0e89ef30.rlib --extern libc=/home/cjr/Developing/phoenix/target/release/deps/liblibc-474e7df688494b8c.rlib --extern log=/home/cjr/Developing/phoenix/target/release/deps/liblog-d9a91e07d7260ab5.rlib --extern memfd=/home/cjr/Developing/phoenix/target/release/deps/libmemfd-6ce2f33a53271fb5.rlib --extern mmap=/home/cjr/Developing/phoenix/target/release/deps/libmmap.so --extern nix=/home/cjr/Developing/phoenix/target/release/deps/libnix-e4dad97c8f270b44.rlib --extern serde=/home/cjr/Developing/phoenix/target/release/deps/libserde-8da27544067defac.rlib --extern socket2=/home/cjr/Developing/phoenix/target/release/deps/libsocket2-6589ddc4d7d243d4.rlib --extern spin=/home/cjr/Developing/phoenix/target/release/deps/libspin-f9a5438f61cd0ce2.rlib --extern static_assertions=/home/cjr/Developing/phoenix/target/release/deps/libstatic_assertions-272e688e1aa9b7d1.rlib --extern thiserror=/home/cjr/Developing/phoenix/target/release/deps/libthiserror-d315377d16479a75.rlib --extern uapi=/home/cjr/Developing/phoenix/target/release/deps/libuapi.so -C prefer-dynamic -C rpath -L native=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out -l ibverbs -l rdmacm -l dylib=rdma_verbs_wrapper -C link-arg=-Wl,-rpath=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out
# unset OUT_DIR


# success
rustc --crate-name rdma --edition=2021 src/rdma/src/lib.rs --crate-type dylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C metadata=ad28b3547ef5f240 --out-dir /home/cjr/Developing/phoenix/target/release/deps -L dependency=/home/cjr/Developing/phoenix/target/release/deps --extern libc=/home/cjr/Developing/phoenix/target/release/deps/liblibc-474e7df688494b8c.rlib --extern log=/home/cjr/Developing/phoenix/target/release/deps/liblog-d9a91e07d7260ab5.rlib --extern memfd=/home/cjr/Developing/phoenix/target/release/deps/libmemfd-6ce2f33a53271fb5.rlib --extern nix=/home/cjr/Developing/phoenix/target/release/deps/libnix-e4dad97c8f270b44.rlib --extern socket2=/home/cjr/Developing/phoenix/target/release/deps/libsocket2-e0b2eca5aebc342c.rlib --extern static_assertions=/home/cjr/Developing/phoenix/target/release/deps/libstatic_assertions-272e688e1aa9b7d1.rlib --extern thiserror=/home/cjr/Developing/phoenix/target/release/deps/libthiserror-9b5981f3c0c4cb95.rlib -C prefer-dynamic -C rpath -L native=/home/cjr/Developing/phoenix/target/release/build/rdma-623128dc1e176758/out -l ibverbs -l rdmacm -l dylib=rdma_verbs_wrapper -C link-arg=-Wl,-rpath=/home/cjr/Developing/phoenix/target/release/build/rdma-623128dc1e176758/out --extern uapi=/home/cjr/Developing/phoenix/target/release/deps/libuapi.so --cfg 'feature="phoenix"'  --extern spin=/home/cjr/Developing/phoenix/target/release/deps/libspin-f9a5438f61cd0ce2.rlib --extern bincode=/home/cjr/Developing/phoenix/target/release/deps/libbincode-157b6e3ae2e1dc50.rlib --extern lazy_static=/home/cjr/Developing/phoenix/target/release/deps/liblazy_static-1fabe01c0e89ef30.rlib #  --extern mmap=/home/cjr/Developing/phoenix/target/release/deps/libmmap.so 

# fail
# rustc --crate-name rdma --edition=2021 src/rdma/src/lib.rs --crate-type dylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="phoenix"' -C metadata=89bd93a55fc087a1 --out-dir /home/cjr/Developing/phoenix/target/release/deps -L dependency=/home/cjr/Developing/phoenix/target/release/deps --extern bincode=/home/cjr/Developing/phoenix/target/release/deps/libbincode-157b6e3ae2e1dc50.rlib --extern lazy_static=/home/cjr/Developing/phoenix/target/release/deps/liblazy_static-1fabe01c0e89ef30.rlib --extern libc=/home/cjr/Developing/phoenix/target/release/deps/liblibc-474e7df688494b8c.rlib --extern log=/home/cjr/Developing/phoenix/target/release/deps/liblog-d9a91e07d7260ab5.rlib --extern memfd=/home/cjr/Developing/phoenix/target/release/deps/libmemfd-6ce2f33a53271fb5.rlib --extern mmap=/home/cjr/Developing/phoenix/target/release/deps/libmmap.so --extern nix=/home/cjr/Developing/phoenix/target/release/deps/libnix-e4dad97c8f270b44.rlib --extern serde=/home/cjr/Developing/phoenix/target/release/deps/libserde-8da27544067defac.rlib --extern socket2=/home/cjr/Developing/phoenix/target/release/deps/libsocket2-6589ddc4d7d243d4.rlib --extern spin=/home/cjr/Developing/phoenix/target/release/deps/libspin-f9a5438f61cd0ce2.rlib --extern static_assertions=/home/cjr/Developing/phoenix/target/release/deps/libstatic_assertions-272e688e1aa9b7d1.rlib --extern thiserror=/home/cjr/Developing/phoenix/target/release/deps/libthiserror-d315377d16479a75.rlib --extern uapi=/home/cjr/Developing/phoenix/target/release/deps/libuapi.so -C prefer-dynamic -C rpath -L native=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out -l ibverbs -l rdmacm -l dylib=rdma_verbs_wrapper -C link-arg=-Wl,-rpath=/home/cjr/Developing/phoenix/target/release/build/rdma-61f156a5d37a5d76/out
