# overwrite with env KOALA_LOG
log_level = "debug"

[tracing]
# overwrite with env KOALA_TRACING
enable = false
# this will log messages level lower than specified into file
# e.g., min_event_level="debug" will log events of "trace" and "debug" to file
# overwrite with env KOALA_MIN_TRACING_EVENT
min_event_level = "trace"
# KOALA_MAX_TRACING_EVENT, this should be equal or more verbose than min_event_level
max_event_level = "trace"
# overwrite with env KOALA_TRACING_SPAN
span_level = "info"
# overwrite with env KOALA_TRACING_DIR
output_dir = "/tmp/koala-trace"

[profiling]
# overwrite with env KOALA_PROFILING_ENABLE_ON_NEW_CLIENT
enable_on_new_client = true
# overwrite with env KOALA_PROFILING_DURATION_MS
duration_ms = 1000

# [runtime]
# max_dedicate = 10

[control]
# overwrite with KOALA_PREFIX
prefix = "/tmp/koala"
# overwrite with KOALA_CONTROL
path = "control.sock"

# Modules
[[modules]]
name = "RdmaTransport"
lib_path = "/tmp/koala/plugins/libkoala_transport_rdma_plugin.so"
config_string = '''
prefix = "/tmp/koala"
engine_basename = "transport-engine-rdma"
datapath_wq_depth = 32
datapath_cq_depth = 32
command_max_interval_ms = 1000
'''

[[modules]]
name = "Salloc"
lib_path = "/tmp/koala/plugins/libkoala_salloc_plugin.so"
config_string = '''
prefix = "/tmp/koala"
engine_basename = "salloc"
'''

[[modules]]
name = "Mrpc"
lib_path = "/tmp/koala/plugins/libkoala_mrpc_plugin.so"
config_string = '''
prefix = "/tmp/koala"
engine_basename = "mrpc-engine"
build_cache = "/tmp/koala/build-cache"
'''

[[modules]]
name = "RpcAdapter"
lib_path = "/tmp/koala/plugins/libkoala_rpc_adapter_plugin.so"


# Addons being here
[[addons]]
name = "RateLimit"
lib_path = "/tmp/koala/plugins/libkoala_ratelimit_plugin.so"
config_string = '''
requests_per_sec = 1000
bucket_size = 1000
'''

[[addons]]
name = "Qos"
lib_path = "/tmp/koala/plugins/libkoala_qos_plugin.so"
config_string = '''
latency_budget_microsecs = 10
'''

[[scheduling]]
service = "Mrpc"
[scheduling.mode]
mode = "GroupShared"
spec = 2