# overwrite with env KOALA_LOG
log_level = "debug"

[tracing]
# overwrite with env KOALA_TRACING
enable = false
# this will log messages level lower than specified into file
# e.g., min_event_level="debug" will log events of "trace" and "debug" to file
# overwrite with env KOALA_MIN_TRACING_EVENT
min_event_level = "trace"
# KOALA_MAX_TRACING_EVENT, this should be equal or more verbose than min_event_level
max_event_level = "trace"
# overwrite with env KOALA_TRACING_SPAN
span_level = "info"
# overwrite with env KOALA_TRACING_DIR
output_dir = "/tmp/koala-trace"

[profiling]
# overwrite with env KOALA_PROFILING_ENABLE_ON_NEW_CLIENT
enable_on_new_client = true
# overwrite with env KOALA_PROFILING_DURATION_MS
duration_ms = 1000

# [runtime]
# max_dedicate = 10

[control]
# overwrite with KOALA_PREFIX
prefix = "/tmp/koala"
# overwrite with KOALA_CONTROL
path = "control.sock"

[[modules]]
name = "Salloc"
lib_path = "/tmp/koala/plugins/libkoala_salloc_plugin.so"

[[modules]]
name = "RdmaTransport"
lib_path = "/tmp/koala/plugins/libkoala_transport_rdma_plugin.so"

[[modules]]
name = "RpcAdapter"
lib_path = "/tmp/koala/plugins/libkoala_rpc_adapter_plugin.so"

[[modules]]
name = "Mrpc"
lib_path = "/tmp/koala/plugins/libkoala_mrpc_plugin.so"

[[addons]]
name = "RateLimit"
lib_path = "/tmp/koala/plugins/libkoala_ratelimit_plugin.so"
