log_env = "KOALA_LOG"
default_log_level = "debug"

modules = ["transport", "mrpc"]

[control]
prefix = "/tmp/koala"
path = "/tmp/koala-control.sock"

[transport]
prefix = "/tmp/koala"
engine_basename = "koala-transport-engine"
datapath_wq_depth = 32
datapath_cq_depth = 32
command_max_interval_ms = 1000

[mrpc]