event_env = "KOALA_LOG"
span_env = "KOALA_PROFILE"
default_tracing_level = "error"
# log_dir = "/tmp/koala-log"

# modules = ["transport-rdma", "transport-tcp", "mrpc", "rpc-adapter", "overload"]
modules = ["Mrpc", "RpcAdapter", "Overload"]

[control]
prefix = "/tmp/koala"
path = "koala-control.sock"

[mrpc]
prefix = "/tmp/koala"
engine_basename = "koala-mrpc-engine"

[salloc]
prefix = "/tmp/koala"
engine_basename = "koala-salloc"

[transport-tcp]
prefix = "/tmp/koala"
engine_basename = "koala-transport-engine-tcp"

[transport-rdma]
prefix = "/tmp/koala"
engine_basename = "koala-transport-engine-rdma"
datapath_wq_depth = 32
datapath_cq_depth = 32
command_max_interval_ms = 1000

[[node]]
id = "mrpc.0"
type = "Mrpc"

# [[node]]
# id = "overload"
# type = "Overload"

[[node]]
id = "rpc-adapter"
type = "RpcAdapter"

[edges]
egress = [
  ["mrpc.0", "rpc-adapter"],
]
# egress = [
#   ["mrpc.0", "overload"],
#   ["overload", "rpc-adapter"],
# ]
ingress = [
  ["rpc-adapter", "mrpc.0"],
]
