[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.echo]
script = ["echo hello from workspace"]

[tasks.format]
install_crate = "rustfmt"
script = { file = "${CARGO_MAKE_WORKING_DIRECTORY}/format.sh", absolute_path = true }
# script = [
#     "scripts/format.sh"
# ]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.prebuild]
command = "cargo"
args = ["build"]

[tasks.deploy-plugins]
script = { file = "${CARGO_MAKE_WORKING_DIRECTORY}/deploy_plugins.sh", absolute_path = true }
dependencies = ["prebuild"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["deploy-plugins"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["deploy-plugins"]

[tasks.rr]
command = "cargo"
args = ["rr"]
dependencies = ["deploy-plugins"]
