name = "masstree_analytics/workload_mp"
description = "Masstree analytics workload: 4 client/server pairs multiple process"
group = "masstree_analytics"
timeout_secs = 15

[[worker]]
host = "danyang-06"
bin = "masstree_analytics_server"
args = """\
  --num-keys 1000000 \
  --num-server-fg-threads 1 \
  --num-server-bg-threads 2 \
  --server-port 5000 \
"""

[[worker]]
host = "danyang-06"
bin = "masstree_analytics_server"
args = """\
  --num-keys 1000000 \
  --num-server-fg-threads 1 \
  --num-server-bg-threads 2 \
  --server-port 5001 \
"""

[[worker]]
host = "danyang-06"
bin = "masstree_analytics_server"
args = """\
  --num-keys 1000000 \
  --num-server-fg-threads 1 \
  --num-server-bg-threads 2 \
  --server-port 5002 \
"""

[[worker]]
host = "danyang-06"
bin = "masstree_analytics_server"
args = """\
  --num-keys 1000000 \
  --num-server-fg-threads 1 \
  --num-server-bg-threads 2 \
  --server-port 5003 \
"""

[[worker]]
host = "danyang-05"
bin = "masstree_analytics_client"
args = """\
  --test-ms 10000 \
  --num-client-threads 1 \
  --req-window 8 \
  --num-keys 1000000 \
  --range-size 128 \
  --range-req-percent 1 \
  --server-port 5000 \
  --server-addr rdma0.danyang-06 \
  --num-server-fg-threads 1 \
"""
dependencies = [0, 1, 2, 3]

[[worker]]
host = "danyang-05"
bin = "masstree_analytics_client"
args = """\
  --test-ms 10000 \
  --num-client-threads 1 \
  --req-window 8 \
  --num-keys 1000000 \
  --range-size 128 \
  --range-req-percent 1 \
  --server-port 5001 \
  --server-addr rdma0.danyang-06 \
  --num-server-fg-threads 1 \
"""
dependencies = [0, 1, 2, 3]

[[worker]]
host = "danyang-05"
bin = "masstree_analytics_client"
args = """\
  --test-ms 10000 \
  --num-client-threads 1 \
  --req-window 8 \
  --num-keys 1000000 \
  --range-size 128 \
  --range-req-percent 1 \
  --server-port 5002 \
  --server-addr rdma0.danyang-06 \
  --num-server-fg-threads 1 \
"""
dependencies = [0, 1, 2, 3]

[[worker]]
host = "danyang-05"
bin = "masstree_analytics_client"
args = """\
  --test-ms 10000 \
  --num-client-threads 1 \
  --req-window 8 \
  --num-keys 1000000 \
  --range-size 128 \
  --range-req-percent 1 \
  --server-port 5003 \
  --server-addr rdma0.danyang-06 \
  --num-server-fg-threads 1 \
"""
dependencies = [0, 1, 2, 3]
