[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc-channel = "0.15.0"
thiserror = "1.0.29"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
engine = { path = "../engine" }