[package]
name = "masstree_analytics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.48"
mrpc-build = { path = "../../mrpc/mrpc-build" }

[dependencies]
mrpc = { path = "../../mrpc" }
prost = { path = "../../3rdparty/prost", features = ["mrpc-frontend"] }

chrono = "0.4.19"
env_logger = "0.9.0"
fasthash = "0.4.0"
link-cplusplus = "1.0"
log = "0.4.17"
nix = { version = "0.24.1", features = ["signal"], default-features = false }
structopt = { version = "0.3.23", features = ["color", "suggestions", "doc"] }
smol = "1.2.5"
minstant = "0.1.1"
futures = "0.3.21"
fastrand = "1.7.0"
arc-swap = "1.5.0"
crossbeam-utils = "0.8.10"

[[bin]]
name = "masstree_analytics_client"
path = "src/client.rs"

[[bin]]
name = "masstree_analytics_server"
path = "src/server.rs"
