name = "benchmark/write_tput/write_tput-32b-4c-4s-8q"
description = "Run RPS benchmark for RDMA write 4 client threads and 4 server threads, each with 8 QPs"
group = "write_tput"
timeout_secs = 60

[[worker]]
host = "danyang-06"
bin = "bench_bw"
args = "write -n 1000000 -s 32 --port 5000 --num-qp 8 --num-client-threads 4 --num-server-threads 4"

[[worker]]
host = "danyang-05"
bin = "bench_bw"
args = "write -n 1000000 -s 32 -c rdma0.danyang-06 --port 5000 --num-qp 8 --num-client-threads 4 --num-server-threads 4"
dependencies = [0]
