[package]
name = "mrpc-derive"
version = "0.1.0"
edition = "2021"


[lib]
proc_macro = true

[dependencies]
anyhow = "1.0.57"
itertools = "0.10"
proc-macro2 = "1"
quote = "1"
syn = { version = "1.0.96", features = [ "extra-traits" ] }
thiserror = "1.0"