[package]
name = "salloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mmap = { path = "../../mmap" }
slabmalloc = { path = "../../slabmalloc" }
libkoala = { path = "../../libkoala" }
interface = { path = "../../interface" }
ipc = { path = "../../ipc", features = ["salloc"] }
shm = { path = "../../shm" }

nix = "0.25.0"
lazy_static = "1.4.0"
smol = "1.2.5"
memfd = "0.4.1"
spin = "0.9.2"
tracing = "0.1"
thiserror = "1.0.29"
