[package]
name = "rpc_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
mrpc-build = { path = "../../mrpc/mrpc-build" }

[dependencies]
mrpc = { path = "../../mrpc" }
prost = { path = "../../3rdparty/prost", features = ["mrpc-frontend"] }

structopt = "0.3.23"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
futures = "0.3"
smol = "1.2.5"
minstant = "0.1.1"
hdrhistogram = "7.5.0"


[[bin]]
name = "rpc_bench_client"
path = "src/client.rs"

[[bin]]
name = "rpc_bench_server"
path = "src/server.rs"

[[bin]]
name = "rpc_bench_brusty_client"
path = "src/brusty_client.rs"