[package]
name = "send_lat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libkoala = { path = "../../libkoala" }

structopt = "0.3.23"
