[package]
name = "phoenix-hotel-acl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
minstant = "0.1.1"
thiserror = "1.0.31"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.81"
anyhow = "1.0.58"
nix = "0.23.0"
toml = { version = "0.5.8", features = ["preserve_order"] }
bincode = "1.3.3"
fnv = "1.0.7"

phoenix = { path = "../../../phoenix" }
ipc = { path = "../../../ipc", features = ["hotel-acl"] }
mrpc-marshal = { path = "../../../mrpc-marshal" }
mrpc-derive = { path = "../../../mrpc-derive" }
shm = { path = "../../../shm" }
interface = { path = "../../../interface" }
# prost = { path = "../../../3rdparty/prost", features = ["mrpc-frontend"] }
