[package]
name = "ipc-ratelimit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc-core = { path = "../../core" }
interface = { path = "../../../interface" }

serde = { version = "1.0.130", features = ["derive"] }
static_assertions = "1.1.0"