[package]
name = "hotel_reservation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
mrpc-build = { path = "../../mrpc/mrpc-build" }

[dependencies]
mrpc = { path = "../../mrpc" }
prost = { path = "../../3rdparty/prost", features = ["mrpc-frontend"] }

structopt = "0.3.23"
futures = "0.3"
smol = "1.2.5"
minstant = "0.1.1"
hdrhistogram = "7.5.0"
fastrand = "1.7.0"


[[bin]]
name = "hotel_reservation_client"
path = "src/client.rs"

[[bin]]
name = "hotel_reservation_server"
path = "src/server.rs"
