name = "benchmark/rpc_bench_rate/rpc_bench_rate_32b_4c"
description = "Small RPC rate and scalability"
group = "rpc_bench_rate"
timeout_secs = 15

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = "--num-server-threads 4"

[[worker]]
host = "danyang-05"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-06 --concurrency 128 --req-size 32 -D 10 -i 1 --num-client-threads 4 --num-server-threads 4 -l info"
dependencies = [0]
