[package]
name = "slabmalloc"
version = "0.10.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
description = "Simple slab based malloc implementation in rust. Can be used stand-alone or in order to provide the necessary interface to rusts liballoc library. slabmalloc only relies on libcore."
homepage = "https://github.com/gz/rust-slabmalloc"
repository = "https://github.com/gz/rust-slabmalloc"
documentation = "https://docs.rs/slabmalloc"
readme = "README.md"
license = "MIT"
edition = "2018"

keywords = ["os", "malloc", "slab", "alloc", "memory"]

[features]
unstable = []
default = [ "unstable" ]

[dependencies]
log = "0.4"
arrayvec = { version = "0.7", default-features = false }
spin = "0.9.3"
lazy_static = "1.4.0"

[target.'cfg(unix)'.dev-dependencies]
rand = "0.8"
env_logger = "0.9"
