[package]
name = "koala"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
chrono = "0.4.19"
anyhow = "1.0.44"
thiserror = "1.0.29"
crossbeam = "0.8.1"
uuid = "0.8.2"
num_cpus = "1.13.0"
nix = "0.23.0"
libc = "0.2.103"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
engine = { path = "../engine" }
interface = { path = "../interface" }
ipc = { path = "../ipc" }
rdma = { path = "../rdma", features = ["koala"] }
fnv = "1.0.7"
mio = { version = "0.7.13", features = ["os-poll", "os-ext"] }
lazy_static = "1.4.0"
