mod dispatch;
mod prost;
mod cache;

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub struct MethodIdentifier(u32, u32);

#[derive(Clone, Debug)]
pub struct RpcMethodInfo {
    pub service_id: u32,
    pub func_id: u32,
    // fully qualified path for the method's input rust type
    // for extern path, should start with "::"
    // for local path that generated by prost-build,
    // should start with the package name, e.g., `foo::bar::HelloRequest`
    // instead of starting with "::" qualifier
    pub input_type: String,
    // output type's path
    pub output_type: String    
} 

pub fn build_dispatch_library() {
    
}