name = "benchmark/rpc_bench_tput/rpc_bench_tput_8mb"
description = "Run rpc_bench benchmark"
group = "rpc_bench_tput"
timeout_secs = 20

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = ""

[[worker]]
host = "danyang-05"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-06 --concurrency 32 --req-size 8000000 -D 10 -i 1"
dependencies = [0]
