name = "benchmark/rpc_bench_tput/rpc_bench_tput_512kb"
description = "Run rpc_bench benchmark"
group = "rpc_bench_tput"
timeout_secs = 15

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = ""

[[worker]]
host = "danyang-05"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-06 --concurrency 32 --req-size 524288 -D 10 -i 1 -l info"
dependencies = [0]
