[alias]     # command aliases
rr = "run --release"
build-plan = "build --build-plan -Z unstable-options"

[env]
RUST_BACKTRACE = "1"

[build]
# link libphoenix and all engine plugins as dynamic library
rustflags = ["-C", "prefer-dynamic", "-C", "rpath"]
