[package]
name = "hotel_microservices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
mrpc-build = { path = "../../mrpc/mrpc-build" }

[dependencies]
mrpc = { path = "../../mrpc" }
prost = { path = "../../3rdparty/prost", features = ["mrpc-frontend"] }

structopt = "0.3.23"
futures = "0.3"
smol = "1.2.5"
anyhow = "1.0.64"
mongodb = { version = "2.3.0", features = ["tokio-sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kdtree = "0.6.0" 
geo = "0.23.0"
chrono = "0.4.22"
env_logger = "0.9.0"
log = "0.4.17"
memcache = "0.16.0"
tokio = { version = "1.21.0", features = ["rt"] }
hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }
url = "2.3.1"
async-ctrlc = "1.2.0"
minstant = "0.1.2"
thiserror = "1.0.34"
csv = "1.1.6"

[[bin]]
name = "hotel_reserv_geo"
path = "src/geo/main.rs"

[[bin]]
name = "hotel_reserv_rate"
path = "src/rate/main.rs"

[[bin]]
name = "hotel_reserv_search"
path = "src/search/main.rs"

[[bin]]
name = "hotel_reserv_profile"
path = "src/profile/main.rs"

[[bin]]
name = "hotel_reserv_frontend"
path = "src/frontend/main.rs"