name = "policy/null/rpc_bench_latency_64b"
description = "Run rpc_bench benchmark"
group = "null"
timeout_secs = 40

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = ""

[[worker]]
host = "danyang-05"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-06 --concurrency 1 --req-size 64 -t 65536"
dependencies = [0]
