[package]
name = "socket_lat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.7"


[[bin]]
name = "socket_sender"
path = "src/sender.rs"

[[bin]]
name = "socket_receiver"
path = "src/receiver.rs"
