name = "benchmark/rpc_bench_latency/brpc_bench_latency_1024b"
description = "Run rpc_bench benchmark"
group = "rpc_bench_latency"
timeout_secs = 10

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = ""

[[worker]]
host = "danyang-05"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-06 --concurrency 1 --req-size 1024"
dependencies = [0]
