[package]
name = "koala-transport-rdma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib"]

[dependencies]
interface = { path = "../../interface" }
ipc = { path = "../../ipc" }
koala = { path = "../../koala" }
rdma = { path = "../../rdma", features = ["koala"] }

tokio = { version = "1.18.2", features = ["sync"] }
anyhow = "1.0.58"
lazy_static = "1.4.0"
tracing = "0.1"
nix = "0.23.0"
uuid = "0.8.2"
thiserror = "1.0.31"
spin = "0.9.3"
fnv = "1.0.7"
mio = { version = "0.7.13", features = ["os-poll", "os-ext"] }
futures = "0.3.21"
memoffset = "0.6.5"
serde = { version = "1.0.130", features = ["derive"] }
toml = { version = "0.5.8", features = ["preserve_order"] }