[package]
name = "dispatch"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
mrpc-derive = {{ path = "{mrpc_derive}" }}
mrpc-marshal = {{ path = "{mrpc_marshal}" }}
shm = {{ path = "{shm}" }}
interface = {{ path = "{interface}" }}
spin = "0.9.3"
