addon_engine = "RateLimitEngine"
tx_channels_replacements = [
    ["MrpcEngine", "RateLimitEngine", 0, 0],
    ["RateLimitEngine", "RpcAdapterEngine", 0, 0],
]
rx_channels_replacements = []
group = ["MrpcEngine", "RpcAdapterEngine"]
op = "attach"
config_string = '''
requests_per_sec = 100000
bucket_size = 1000
'''
