addon_engine = "RateLimitEngine"
tx_channels_replacements = [
    ["MrpcEngine", "RateLimitEngine", 0, 0],
    ["RateLimitEngine", "RpcAdapterEngine", 0, 0],
]
rx_channels_replacements = []
group = ["MrpcEngine", "RpcAdapterEngine"]
op = "attach"