[package]
name = "mrpc-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost-build = { path = "../../3rdparty/prost/prost-build", features = ["mrpc-frontend"] }

prettyplease = {version = "0.1"}
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
crc32fast = "1.3.2"
