[package]
name = "send_bw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libphoenix = { path = "../../libphoenix" }

structopt = "0.3.23"
