name = "launch_koala"
description = "Launch koala daemon"
group = "launch_koala"
timeout_secs = 600

[[worker]]
host = "danyang-05"
bin = "koala"
args = "-c eval/policy/qos/koala_client.toml"

[[worker]]
host = "danyang-06"
bin = "koala"
args = "-c eval/policy/qos/koala_server.toml"
dependencies = [0] # launch in order, no very necessary
