[package]
name = "ipc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interface = { path = "../../interface" }

ipc-channel = "0.15.0"
thiserror = "1.0.29"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
libc = "0.2.103"
shmem-ipc = "0.2.0"
zerocopy = "0.3.0"
memfd = "0.4.1"
memmap2 = "0.5.0"
uuid = "0.8.2"
atomic-traits = "0.3.0"
nix = "0.23.0"
crossbeam = "0.8.1"
unique = "0.9.1"
minstant = "0.1.1"
