name: build Phoenix

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build phoenix, run tests and fmt
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      env:
        DEPLOY_KEY_PROST: ${{ secrets.DEPLOY_KEY_PROST }}
      run: |
        mkdir $HOME/.ssh && echo "${DEPLOY_KEY_PROST}" > $HOME/.ssh/id_ed25519 && chmod 600 $HOME/.ssh/id_ed25519
        git submodule update --init --recursive

    - name: Install RDMA library
      run: sudo apt install -y rdma-core libibverbs-dev librdmacm-dev libnuma-dev

    - name: Install nightly rust toolchain
      run: rustup show

    - name: Run cargo check
      run: cargo check

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1

    - name: Build phoenixos
      run: cargo make build-phoenixos

    - name: Build phoenix plugins
      run: cargo make build-phoenix-plugins

    - name: Build phoenix-cli tools
      run: cargo make build-phoenix-cli

    - name: Run cargo test
      run: cargo test
      env:
        RUST_BACKTRACE: 1

    - name: Run cargo clippy
      run: cargo clippy

    - name: Check formatting
      run: cargo fmt --all -- --check
