addon_engine = "HotelAclEngine"
tx_channels_replacements = [
    ["MrpcEngine", "HotelAclEngine", 0, 0],
    ["HotelAclEngine", "TcpRpcAdapterEngine", 0, 0],
]
rx_channels_replacements = [
    ["TcpRpcAdapterEngine", "HotelAclEngine", 0, 0],
    ["HotelAclEngine", "MrpcEngine", 0, 0],
]
group = ["MrpcEngine", "TcpRpcAdapterEngine"]
op = "attach"
config_string = '''
'''
