name = "benchmark/hotel_reservation"
description = "Run hotel_reservation rate test"
group = "hotel_reservation"
timeout_secs = 70

[[worker]]
host = "danyang-06"
bin = "hotel_reservation_server"
args = "--transport tcp"

[[worker]]
host = "danyang-05"
bin = "hotel_reservation_client"
args = "--transport tcp -c rdma0.danyang-06 --concurrency 128 -D 65 -i 1"
dependencies = [0]
