name = "launch_phoenix"
description = "Launch phoenix daemon"
group = "launch_phoenix"
timeout_secs = 600

[[worker]]
host = "danyang-05"
bin = "phoenix"
args = "-c eval/policy/hotel-acl/phoenix.toml --no-ansi"

[[worker]]
host = "danyang-06"
bin = "phoenix"
args = "-c eval/policy/hotel-acl/phoenix.toml --no-ansi"
dependencies = [0] # launch in order, not very necessary
