name = "benchmark/rpc_bench"
description = "Run rpc_bench benchmark"
group = "rpc_bench"

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = ""

[[worker]]
host = "danyang-05"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-06"