name = "benchmark/send_bw-64kb"
description = "Run bandwidth benchmark for send/recv"
group = "send_bw"
timeout_secs = 10

[[worker]]
host = "danyang-06"
bin = "send_bw"
args = ""
dependencies = []

[[worker]]
host = "danyang-05"
bin = "send_bw"
args = "-c rdma0.danyang-06"
dependencies = [0]
