name = "benchmark/write_bw-1mb"
description = "Run bandwidth benchmark for RDMA write"
group = "write_bw"

[[worker]]
host = "danyang-06"
bin = "bench_bw"
args = "write -n 10000 -s 1048576"

[[worker]]
host = "danyang-05"
bin = "bench_bw"
args = "write -n 10000 -c rdma0.danyang-06 -s 1048576"