name = "benchmark/write_bw-1mb"
description = "Run bandwidth benchmark for RDMA write"
group = "write_bw"
timeout_secs = 10

[[worker]]
host = "danyang-06"
bin = "bench_bw"
args = "write -n 10000 -s 1048576"
dependencies = []

[[worker]]
host = "danyang-05"
bin = "bench_bw"
args = "write -n 10000 -c rdma0.danyang-06 -s 1048576"
dependencies = [0]
